export const globalVariable = {
    URL_BASE: 'https://localhost:44333',
    URL_API: 'https://localhost:44333/api',
    // URL_BASE: 'http://10.192.50.54:4000',
    // URL_API: 'http://10.192.50.54:4000/api',
    // URL_BASE: 'http://10.5.88.76:4000',
    // URL_API: 'http://10.5.88.76:4000/api',
    DIR_SELECTED: '/',
    SEARCH_TEXT: '',
    RUNNING_DOCKER: false,
    DIR_E: 'E:\\Drive_W',
    DIR_DATA_E: 'E:\\Drive_W\\Data\\',
    TAB_DOCUMENTS: 'tab_documents',
    TAB_IMAGES: 'tab_images',
    TAB_FOLDERS: 'tab_folders',
    TAB_RIGHT_ROLES: 'tab_rights_roles',
    TAB_GENERAL: 'tab_general',
    TAB_HISTORY: 'tab_history',
    TAB_CURRENT: 'tab_documents',
    TITLE_NUMBER_OF_FILE: 'Number of Documents',
    STATUS_DRAGGING_FILE: false,
    COLOR: '#bbdefb',
    Author:'Author',
    USER_INFO: {
        id: 0,
        fullName: '',
        userID: '',
        email: '',
        password: '',
        jobID: 0,
        kipID: 0,
        workID: 0,
        areaID: 0,
        isActive: 0,
        language: 0,
        jobName: '',
        phone: '',
        admin: 0
    },
    GENERAL_DIRECTORY: {
        name: '',
        fullname: '',
        type: '',
        location: '',
        files: 0,
        directories: 0,
        size: "",
        length: '',
        creationTime: '',
        lastWriteTime: '',
        lastAccessTime: ''
    },
    COLUMN_CONFIGURATION: {
        author: true,
        last_check_in: true,
        status: true,
        revision: true,
        size: true,
        autom_rev: true,
        description: true,
        language: true,
        sheet: true,
        document_number: true,
    },
    FILTER_ROWS: {
        is_active: false,
        title_value: '',
        title_option: '',
        last_check_in: '',
        last_check_in_day: '',
        last_check_in_month: '',
        last_check_in_year: '',
        author: '',
        status: '',
        version: '',
        size_from_value: '',
        size_from_option: '',
        size_to_value: '',
        size_to_option: '',
        autom_rev: '',
        description: '',
        document_number: '',
    },
    DATA_RESPONSE_REFRESH: '',
    PAGE_CURRENT: 'home',
    TEXT_LAYOUT: 'List layout',
    isAllowUpdateBookmark: true,
    keySearch:false,
    isIndexTabSelected: 3, // Home
};